package com.kree.keehoo.yourcarinfo.DaoGeneratedFiles;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carDaoConfig;

    private final CarDao carDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carDaoConfig = daoConfigMap.get(CarDao.class).clone();
        carDaoConfig.initIdentityScope(type);

        carDao = new CarDao(carDaoConfig, this);

        registerDao(Car.class, carDao);
    }
    
    public void clear() {
        carDaoConfig.getIdentityScope().clear();
    }

    public CarDao getCarDao() {
        return carDao;
    }

}
